
auth.token=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

defaults.org=it-path-solutions-41
defaults.project=react-native

defaults.url=https://sentry.io/
