import HomeHeader from '@components/atoms/CustomHeader';
import { logout } from '@redux/slices/AuthSlice';

export const IMAGES = {
  First: require('./images/firstScreen.png'),
  SecondOnboarding: require('./images/onboardingSecond.png'),
  OnboardingThree: require('./images/onboardingThree.png'),
  Home: require('./images/home.png'),
  ImageMedia: require('./images/image-media.png'),
  More: require('./images/more.png'),
  ScanQR: require('./images/scanQR.png'),
  VideoMedia: require('./images/video-media.png'),
  Allio_Logo: require('./images/Allio_logo.png'),
  Mobile: require('./images/mobile.png'),
  Notification: require('./images/notification.jpg'),
  Scanner: require('./images/scanner.jpg'),
  Homeimage: require('./images/homeimage.png'),
  Two: require('./images/two.png'),
  Deleteimage: require('./images/icondelete.png'),
  Logout: require('./images/logoutimag.png'),
};

export const ICONS = {
  eye: require('./icons/eye.png'),
  eyeOff: require('./icons/eyeoff.png'),
  down: require('./icons/arrowdown.png'),
  check: require('./icons/check.png'),
  cancel: require('./icons/cancel.png'),
  logout: require('./icons/logout.png'),
  Clear: require('./icons/clear.png'),
  FaceBook: require('./icons/facebook.png'),
  Google: require('./icons/googleicon.png'),
  LinkedIn: require('./icons/message.png'),
  Github: require('./icons/github.png'),
  ArrowRight: require('./icons/right-arrow.png'),
  mpinSecure: require('./icons/mobilesecure.png'),
  gallery: require('./icons/gallery.png'),
  compressed: require('./icons/compressed.png'),
  NoVideo: require('./icons/video.png'),
  profile: require('./icons/profile.png'),
  Left: require('./icons/arrow.png'),
};
export const FONTS = {
  regular: 'Montserrat-Regular',
  medium: 'Montserrat-Medium',
  bold: 'Montserrat-Bold',
  semiBold: 'Montserrat-SemiBold',
  light: 'Montserrat-Light',
  extraBold: 'Montserrat-ExtraBold',
  extraLight: 'Montserrat-ExtraLight',
  black: 'Montserrat-Black',
  italic: 'Montserrat-Italic',
  VideoPlay: require('./icons/videoPlay.png'),
  Share: require('./icons/share.png'),
  Send: require('./icons/send.png'),
  Download: require('./icons/download.png'),
  light: require('./icons/light.png'),
};
