export const IMAGES = {
  First: require('./images/firstScreen.png'),
  SecondOnboarding: require('./images/onboardingSecond.png'),
  OnboardingThree: require('./images/onboardingThree.png'),
  Dummy_Profile: require('./images/Dummy_Profile.png'),
  Allio_Logo: require('./images/Allio_logo.png'),
  Mobile: require('./images/mobile.png'),
  Notification: require('./images/notification.jpg'),
  Deleteimage: require('./images/icondelete.png'),
  Nodata: require('./images/Nodata.png'),
  Chattheme1: require('./images/chattheme1.jpg'),
  Chattheme2: require('./images/chattheme2.jpg'),
  Chattheme3: require('./images/chattheme3.jpg'),
  Chattheme4: require('./images/chattheme4.jpg'),
};

export const ICONS = {
  eye: require('./icons/eye.png'),
  eyeOff: require('./icons/eyeoff.png'),
  down: require('./icons/arrowdown.png'),
  check: require('./icons/check.png'),
  cancel: require('./icons/cancel.png'),
  BackArrow: require('./icons/simple-backArrow.png'),
  Clear: require('./icons/clear.png'),
  FaceBook: require('./icons/facebook.png'),
  Google: require('./icons/googleicon.png'),
  LinkedIn: require('./icons/message.png'),
  Github: require('./icons/github.png'),
  mpinSecure: require('./icons/mobilesecure.png'),
  gallery: require('./icons/gallery.png'),
  NoVideo: require('./icons/video.png'),
  profile: require('./icons/profile.png'),
  VideoPlay: require('./icons/videoPlay.png'),
  Share: require('./icons/share.png'),
  Send: require('./icons/send.png'),
  Download: require('./icons/download.png'),
  light: require('./icons/light.png'),
  true: require('./icons/true.png'),
  false: require('./icons/false.png'),
  menu: require('./icons/menu.png'),
  stop: require('./icons/stop.png'),
  copy: require('./icons/copy.png'),
  Attach: require('./icons/attach.png'),
  gemini: require('./icons/Geminiai.png'),
  Edit: require('./icons/edit.png'),
  Social: require('./icons/social.png'),
  Home: require('./icons/home.png'),
  ImageMedia: require('./icons/image-media.png'),
  ScanQR: require('./icons/scanQR.png'),
  VideoMedia: require('./icons/video-media.png'),
  More: require('./icons/more.png'),
  Chat: require('./icons/chat.png'),
  Logout: require('./icons/logoutIcon.png'),
  drag: require('./icons/drag.png'),
};

export const FONTS = {
  regular: 'Montserrat-Regular',
  medium: 'Montserrat-Medium',
  bold: 'Montserrat-Bold',
  semiBold: 'Montserrat-SemiBold',
  light: 'Montserrat-Light',
  extraBold: 'Montserrat-ExtraBold',
  extraLight: 'Montserrat-ExtraLight',
  black: 'Montserrat-Black',
  italic: 'Montserrat-Italic',
};
